### ISSUE TITLE
inch terminates with exception 

### ISSUE THREAD

**Issue by doudou** [rrrene/inch#33]
Backtrace

~~~
/home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/language/ruby/provider/yard/object/method_object.rb:162:in `block in return_described_via_tag?': undefined method `empty?' for nil:NilClass (NoMethodError)
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/language/ruby/provider/yard/object/method_object.rb:160:in `each'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/language/ruby/provider/yard/object/method_object.rb:160:in `any?'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/language/ruby/provider/yard/object/method_object.rb:160:in `return_described_via_tag?'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/language/ruby/provider/yard/object/method_object.rb:86:in `return_described?'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/code_object/converter.rb:75:in `public_send'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/code_object/converter.rb:75:in `block in to_hash'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/code_object/converter.rb:73:in `each'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/code_object/converter.rb:73:in `to_hash'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/code_object/proxy.rb:14:in `for'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/object.rb:32:in `initialize'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/objects.rb:19:in `new'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/objects.rb:19:in `block in initialize'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/objects.rb:18:in `map'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/objects.rb:18:in `initialize'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/proxy.rb:7:in `new'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/proxy.rb:7:in `initialize'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/proxy.rb:12:in `new'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase/proxy.rb:12:in `parse'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/codebase.rb:12:in `parse'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/cli/command/base_list.rb:24:in `prepare_codebase'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/cli/command/suggest.rb:24:in `run'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/cli/command/base.rb:50:in `run'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/cli/command_parser.rb:99:in `run_command'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/cli/command_parser.rb:62:in `run'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/lib/inch/cli/command_parser.rb:52:in `run'
        from /home/doudou/dev/flat_fish/.gems/gems/inch-0.6.3/bin/inch:23:in `<top (required)>'
        from /home/doudou/dev/flat_fish/.gems/bin/inch:23:in `load'
        from /home/doudou/dev/flat_fish/.gems/bin/inch:23:in `<main>'
~~~

I would happily try to isolate the file that triggers the bug ... but is there a way to trace what inch is doing ?

**Comment by rrrene** [comment]
Hi Sylvain,

I just pushed Inch `0.6.4` which should solve your problem!

**Comment by doudou** [comment]
It indeed does. Thanks.
